# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('rel_date', models.DateTimeField(verbose_name='date release')),
                ('imdb_url', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Movie')),
                ('rater', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Rater')),
            ],
        ),
    ]
