# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rel_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 9, 14, 43, 22, 675127, tzinfo=utc), verbose_name='date added'),
            preserve_default=False,
        ),
    ]
