# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20160509_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='add_date',
            field=models.DateField(verbose_name='date added'),
        ),
    ]
