# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20160509_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='add_date',
            new_name='date_added',
        ),
    ]
